scController: main.cpp
	g++ main.cpp -g -Wall -o gui_controller.out MackieSenderReceiverMidi.o `wx-config --cxxflags` `wx-config --libs` -L/home/samuel/Osc-Sender-Receiver -losc -I/home/samuel/Osc-Sender-Receiver -I/home/samuel/ardour_controller_lw -I/home/samuel/ardour_controller_lw/base_controller/visual_studio  -std=c++17
