OscController: display.cpp MackieControl.cpp OscController.cpp main.cpp
	g++ display.cpp MackieControl.cpp OscController.cpp main.cpp -Wall -g -o osc_controller.out -L/home/samuel/ardour_controller_lw -losc_controller  -L/home/samuel/Osc-Sender-Receiver -losc   -I/home/samuel/Osc-Sender-Receiver -I/home/samuel/ardour_controller_lw -I/home/samuel/ardour_controller_lw/base_controller/visual_studio  -std=c++17 -lasound



